// <auto-generated />
using CUSPIS.Web.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CUSPIS.Web.Migrations
{
    [DbContext(typeof(CuspisDbContext))]
    partial class CuspisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CUSPIS.Web.Models.KontaktOsoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("Fax");

                    b.Property<int>("MjestoId");

                    b.Property<string>("Naziv");

                    b.Property<string>("Telefon");

                    b.Property<string>("Ulica");

                    b.HasKey("Id");

                    b.HasIndex("MjestoId");

                    b.ToTable("KontaktOosobe");

                    b.HasDiscriminator<string>("Discriminator").HasValue("KontaktOsoba");
                });

            modelBuilder.Entity("CUSPIS.Web.Models.Mjesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.HasKey("Id");

                    b.ToTable("Mjesta");
                });

            modelBuilder.Entity("CUSPIS.Web.Models.FizickoLice", b =>
                {
                    b.HasBaseType("CUSPIS.Web.Models.KontaktOsoba");

                    b.Property<string>("JMBG");

                    b.Property<string>("TajniBroj");

                    b.HasDiscriminator().HasValue("FizickoLice");
                });

            modelBuilder.Entity("CUSPIS.Web.Models.PravnoLice", b =>
                {
                    b.HasBaseType("CUSPIS.Web.Models.KontaktOsoba");

                    b.Property<string>("MaticniBroj");

                    b.Property<string>("PIB");

                    b.HasDiscriminator().HasValue("PravnoLice");
                });

            modelBuilder.Entity("CUSPIS.Web.Models.KontaktOsoba", b =>
                {
                    b.HasOne("CUSPIS.Web.Models.Mjesto", "Mjesto")
                        .WithMany()
                        .HasForeignKey("MjestoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
